version: '3.8'

services:
  backend:
    build: ./apps/backend
    ports:
      - "8000:8000"
    volumes:
      - ./apps/backend/uploads:/app/uploads
      - ./apps/backend/outputs:/app/outputs
    environment:
      - UPLOAD_DIR=uploads
      - OUTPUT_DIR=outputs
      - DEFAULT_PAUSE_DURATION=5000
      - DEFAULT_SILENCE_DURATION=1000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build: ./apps/frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
